### ISSUE TITLE
Like BetaWarpaint but for all versions of Xcode

### ISSUE THREAD

**Issue by Ashton-W** [zats/BetaWarpaint#5]
**BetaWarpaint** is really cool, very handy. I really like @orta's [RedXcode](https://github.com/orta/RedXcode) too.

I want to apply these UI indicators to Xcode beta, latest Xcode, and old Xcode apps.
I could PR either project, but I'm think a separate plugin that borrows code and ideas from both, aiming to remain compatible, is easier for users to install and avoids configuration.
This is me asking for permission.

![image](https://cloud.githubusercontent.com/assets/1650398/11419621/c3350b40-947c-11e5-8627-274c79097e4d.png)

**Comment by zats** [comment]
oh, it is very kind of you😀 
this is open source, feel free! 👍

**Comment by Ashton-W** [comment]
Cool! I'll be sure to attribute you both.
